version: "3.9"

services:
  wachterbot:
    container_name: wachterbot-prod
    image: ghcr.io/faangtalk/wachter_bot/wachterbot:prod
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_ERROR_CHAT_ID=${TELEGRAM_ERROR_CHAT_ID}
      - DATABASE_URL=sqlite:////data/db/wachter.db
    restart: unless-stopped
